obstacle_range: 5.0
raytrace_range: 5.0
footprint: [[-0.33,-0.66],[0.33,-0.66],[-0.33,0.5],[0.33,0.5]]
robot_radius: 1.1
inflation_radius: 1.2

observation_sources: laser_scan_sensor 

laser_scan_sensor: { sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true }

